// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool_WebAPI.Data;

namespace SmartSchool_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210306002308_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Alumno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("matricula")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("alumnos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "Kent",
                            matricula = "33225555",
                            nombre = "Marta"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Isabela",
                            matricula = "3354288",
                            nombre = "Paula"
                        },
                        new
                        {
                            id = 3,
                            apellido = "Antonia",
                            matricula = "55668899",
                            nombre = "Laura"
                        },
                        new
                        {
                            id = 4,
                            apellido = "Maria",
                            matricula = "6565659",
                            nombre = "Luiza"
                        },
                        new
                        {
                            id = 5,
                            apellido = "Machado",
                            matricula = "565685415",
                            nombre = "Lucas"
                        },
                        new
                        {
                            id = 6,
                            apellido = "Alvares",
                            matricula = "456454545",
                            nombre = "Pedro"
                        },
                        new
                        {
                            id = 7,
                            apellido = "José",
                            matricula = "9874512",
                            nombre = "Paulo"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.AlumnoMateria", b =>
                {
                    b.Property<int>("alumnoId")
                        .HasColumnType("int");

                    b.Property<int>("materiaId")
                        .HasColumnType("int");

                    b.HasKey("alumnoId", "materiaId");

                    b.HasIndex("materiaId");

                    b.ToTable("alumnoMateria");

                    b.HasData(
                        new
                        {
                            alumnoId = 1,
                            materiaId = 2
                        },
                        new
                        {
                            alumnoId = 1,
                            materiaId = 4
                        },
                        new
                        {
                            alumnoId = 1,
                            materiaId = 5
                        },
                        new
                        {
                            alumnoId = 2,
                            materiaId = 1
                        },
                        new
                        {
                            alumnoId = 2,
                            materiaId = 2
                        },
                        new
                        {
                            alumnoId = 2,
                            materiaId = 5
                        },
                        new
                        {
                            alumnoId = 3,
                            materiaId = 1
                        },
                        new
                        {
                            alumnoId = 3,
                            materiaId = 2
                        },
                        new
                        {
                            alumnoId = 3,
                            materiaId = 3
                        },
                        new
                        {
                            alumnoId = 4,
                            materiaId = 1
                        },
                        new
                        {
                            alumnoId = 4,
                            materiaId = 4
                        },
                        new
                        {
                            alumnoId = 4,
                            materiaId = 5
                        },
                        new
                        {
                            alumnoId = 5,
                            materiaId = 4
                        },
                        new
                        {
                            alumnoId = 5,
                            materiaId = 5
                        },
                        new
                        {
                            alumnoId = 6,
                            materiaId = 1
                        },
                        new
                        {
                            alumnoId = 6,
                            materiaId = 2
                        },
                        new
                        {
                            alumnoId = 6,
                            materiaId = 3
                        },
                        new
                        {
                            alumnoId = 6,
                            materiaId = 4
                        },
                        new
                        {
                            alumnoId = 7,
                            materiaId = 1
                        },
                        new
                        {
                            alumnoId = 7,
                            materiaId = 2
                        },
                        new
                        {
                            alumnoId = 7,
                            materiaId = 3
                        },
                        new
                        {
                            alumnoId = 7,
                            materiaId = 4
                        },
                        new
                        {
                            alumnoId = 7,
                            materiaId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Materia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("profesorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("profesorId");

                    b.ToTable("materia");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Matemática",
                            profesorId = 1
                        },
                        new
                        {
                            id = 2,
                            nombre = "Física",
                            profesorId = 2
                        },
                        new
                        {
                            id = 3,
                            nombre = "Português",
                            profesorId = 3
                        },
                        new
                        {
                            id = 4,
                            nombre = "Inglês",
                            profesorId = 4
                        },
                        new
                        {
                            id = 5,
                            nombre = "Programação",
                            profesorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Profesor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("profesores");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Lauro"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Roberto"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Ronaldo"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Rodrigo"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Alexandre"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.AlumnoMateria", b =>
                {
                    b.HasOne("SmartSchool_WebAPI.Models.Alumno", "alumno")
                        .WithMany()
                        .HasForeignKey("alumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool_WebAPI.Models.Materia", "materia")
                        .WithMany()
                        .HasForeignKey("materiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alumno");

                    b.Navigation("materia");
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Materia", b =>
                {
                    b.HasOne("SmartSchool_WebAPI.Models.Profesor", "profesor")
                        .WithMany("materias")
                        .HasForeignKey("profesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profesor");
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Profesor", b =>
                {
                    b.Navigation("materias");
                });
#pragma warning restore 612, 618
        }
    }
}
